using System;

namespace Fiddler
{
	/// <summary>
	/// This enumeration provides the values for the Session object's BitFlags field
	/// </summary>
	// Token: 0x02000062 RID: 98
	[Flags]
	public enum SessionFlags
	{
		/// <summary>
		/// No flags are set
		/// </summary>
		// Token: 0x04000224 RID: 548
		None = 0,
		/// <summary>
		/// The request originally arrived with a URL specifying the HTTPS protocol.
		/// </summary>
		// Token: 0x04000225 RID: 549
		IsHTTPS = 1,
		/// <summary>
		/// The request originally arrived with a URL specifying the FTP protocol.
		/// </summary>
		// Token: 0x04000226 RID: 550
		IsFTP = 2,
		/// <summary>
		/// Ignore this traffic; do not buffer, store, or call event handlers
		/// </summary>
		// Token: 0x04000227 RID: 551
		Ignored = 4,
		/// <summary>
		/// The client pipe was reused
		/// </summary>
		// Token: 0x04000228 RID: 552
		ClientPipeReused = 8,
		/// <summary>
		/// The server pipe was reused
		/// </summary>
		// Token: 0x04000229 RID: 553
		ServerPipeReused = 16,
		/// <summary>
		/// The request was transmitted to the server when its headers were complete
		/// </summary>
		// Token: 0x0400022A RID: 554
		RequestStreamed = 32,
		/// <summary>
		/// The response was streamed
		/// </summary>
		// Token: 0x0400022B RID: 555
		ResponseStreamed = 64,
		/// <summary>
		/// The request was generated by Fiddler itself (e.g. the Composer tab)
		/// </summary>
		// Token: 0x0400022C RID: 556
		RequestGeneratedByFiddler = 128,
		/// <summary>
		/// The response was generated by Fiddler itself (e.g. AutoResponder or utilCreateResponseAndBypassServer)
		/// </summary>
		// Token: 0x0400022D RID: 557
		ResponseGeneratedByFiddler = 256,
		/// <summary>
		/// This session was loaded from a .SAZ File
		/// </summary>
		// Token: 0x0400022E RID: 558
		LoadedFromSAZ = 512,
		/// <summary>
		///  This session was loaded from some other tool
		/// </summary>
		// Token: 0x0400022F RID: 559
		ImportedFromOtherTool = 1024,
		/// <summary>
		/// This request was sent to an upstream (CERN) gateway proxy
		/// </summary>
		// Token: 0x04000230 RID: 560
		SentToGateway = 2048,
		/// <summary>
		/// This is a "blind" CONNECT tunnel for HTTPS traffic 
		/// </summary>
		// Token: 0x04000231 RID: 561
		IsBlindTunnel = 4096,
		/// <summary>
		/// This is a CONNECT tunnel which decrypts HTTPS traffic as it flows through
		/// </summary>
		// Token: 0x04000232 RID: 562
		IsDecryptingTunnel = 8192,
		/// <summary>
		/// This response was served from a client cache, bypassing Fiddler. Fiddler only "sees" this session because other software reported it to Fiddler
		/// </summary>
		// Token: 0x04000233 RID: 563
		ServedFromCache = 16384,
		/// <summary>
		/// There was a HTTP Protocol violation in the client's request
		/// </summary>
		// Token: 0x04000234 RID: 564
		ProtocolViolationInRequest = 32768,
		/// <summary>
		/// There was a HTTP Protocol violation in the server's response
		/// </summary>
		// Token: 0x04000235 RID: 565
		ProtocolViolationInResponse = 65536,
		/// <summary>
		/// Response body was dropped, e.g due to fiddler.network.streaming.ForgetStreamedData or log-drop-response-body flag
		/// </summary>
		// Token: 0x04000236 RID: 566
		ResponseBodyDropped = 131072,
		/// <summary>
		/// This is a CONNECT tunnel for WebSocket traffic
		/// </summary>
		// Token: 0x04000237 RID: 567
		IsWebSocketTunnel = 262144,
		/// <summary>
		/// This request was sent using the SOCKS protocol
		/// </summary>
		// Token: 0x04000238 RID: 568
		SentToSOCKSGateway = 524288,
		/// <summary>
		/// Request body was dropped, e.g due to log-drop-request-body flag
		/// </summary>
		// Token: 0x04000239 RID: 569
		RequestBodyDropped = 1048576,
		/// <summary>
		/// The request was to create a RPC tunnel (e.g. on an RPC_OUT_DATA request)
		/// </summary>
		// Token: 0x0400023A RID: 570
		IsRPCTunnel = 2097152,
		/// <summary>
		/// If the session was modified by a auto responser rule
		/// </summary>
		// Token: 0x0400023B RID: 571
		IsModifiedByRule = 4194304
	}
}
